// Lexical rules
identifier = .
string = .
number = .
boolean = "true" | "false" .

// Grammar

File = { Definition | Declaration } .

Definition = Preface [ string ] "{" File "}" .

Declaration = Preface [ "=" Expr ] [ string ] ";" . 

QualifiersAndId = { identifier } identifier .

Expr = string | number | boolean | identifier .

Modification = identifier "=" Expr . 

Modifiers = "(" [ Modification { "," Modification } ] ")" .

Preface = QualifiersAndId [ Modifiers ] .

