// Lexical rules
identifier = .
string = .
number = .
boolean = "true" | "false" .

// Grammar

File = { Definition | Declaration } .

QualifiersAndId = identifier { identifier } .

Expr = string | number | boolean .

Modification = identifier "=" Expr . 

Modifiers = "(" [ Modification { "," Modification } ] ")" .

Preface = QualifiersAndId Modifiers string .

Definition = Preface "{" File "}" .

Declaration = Preface [ Ending ] ";" . 

Ending = [ "=" Expr ] string . 
